name: diffdrr
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - pip
  - pytorch=2.2.2
  - torchvision=0.17.2
  - einops
  - matplotlib
  - numpy=1.26.4
  - seaborn
  - imageio
  - fastcore
  - tqdm
  - scipy
  - pip:
    - pyvista
    - timm
    - torchio
    - vtk
