name: diffdrr
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - pip
  - pytorch>2.2,<2.3
  - einops
  - torchvision
  - torchio
  - timm
  - numpy<2
  - matplotlib
  - seaborn
  - imageio
  - fastcore
  - scipy
  - tqdm
  - pyvista
  - vtk
