name: diffdrr
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - pip
  - pytorch>2.2
  - torchvision>0.18
  - einops
  - matplotlib
  - numpy<2
  - seaborn
  - imageio
  - fastcore
  - tqdm
  - scipy
  - pip:
    - pyvista
    - timm
    - torchio
    - vtk
